/**
 * WriteMind's model, with no platform in it at all.
 *
 * Everything here was ported from the macOS app's pure layer — the parser,
 * the formatting commands, the cell and seam arithmetic, the note rows —
 * and the tests beside it were transcribed with it. That is what made the
 * port tractable: the rules already had no AppKit in them, and the suite
 * says so on both sides.
 */

export * from "./text/range"
export * from "./text/find"
// The parser re-exports `Range` from there; everything else is its own.
export {
  blocks, positioned, positionedUpdate, linesOf, heading, isRule, todoItem, bulletItem, dashItem, numberedItem,
  type Hull, type LineSource,
  type Block, type PositionedBlock, type TodoItem,
} from "./markdown/parser"
export * from "./markdown/images"
export * from "./markdown/table"
export * from "./markdown/formatting"
export * from "./markdown/code"
export * from "./markdown/codeTyping"
export * from "./markdown/spans"
export * from "./markdown/sourceStyle"
export * from "./markdown/markerDeletion"
export * from "./markdown/plainText"
export * from "./cells/textCells"
export * from "./text/diff"
export * from "./cells/preview"
export * from "./cells/selection"
export * from "./cells/outline"
export * from "./cells/folding"
export * from "./cells/editing"
export * from "./cells/types"
export * from "./cells/seams"
export * from "./cells/commands"
export * from "./cells/subsections"
export * from "./cells/apart"
export * from "./cells/mathsCells"
export * from "./eval/index"
export * from "./notes/note"
export * from "./notes/order"
export * from "./notes/writing"
export * from "./notes/session"
export * from "./notes/linking"
export * from "./drawing/shapes"
export * from "./drawing/model"
export * from "./drawing/geometry"
export * from "./drawing/groups"
export * from "./drawing/placement"
export * from "./drawing/pen"
export * from "./drawing/routing"
export * from "./drawing/textBox"
export * from "./drawing/ink"
export * from "./drawing/edit"
export * from "./drawing/inkCell"
export * from "./capture/page"
export * from "./capture/warp"
export * from "./capture/findPage"
export * from "./capture/inkVector"
export * from "./capture/cameraZoom"
export * from "./capture/cameraAspect"
export * from "./capture/ink"
export * from "./capture/rects"
export * from "./capture/shapeInk"
export * from "./capture/flowGrouping"
export * from "./capture/flowChart"
export * as handwritingMarks from "./capture/handwritingMarks"
export * from "./capture/textRecognition"
export * from "./math/expression"
export * from "./math/typesetter"
export * from "./math/mathml"
export * from "./math/templates"
export * from "./platform/capabilities"
export * from "./export/pagePlan"
export * from "./export/inline"
export * from "./export/blocks"
export * from "./export/drawing"
export * from "./export/document"
export * from "./export/inkSnapshot"
export * from "./export/formats"
export * from "./export/wolfram/index"
