// /link: type it in one note, point at a part of another (heading, highlighted run, plain block), Cancel,
// and follow links (Alt-click on the markdown, a plain click on the rendered page). (Was wm/links.mjs.)
import { setRendered, ok, finish, js, sleep, seedNotes, openNote, doc, click, insertText, readNoteFile, VIEW, ALT, press, key } from "../../lib/harness.mjs"

await seedNotes({ "Cells.md": "Intro line\n", "Second.md": "# Second\n\nsecond body text\n" }, { clean: true })
await openNote("Cells")
const endOfDoc = () => js(`${VIEW}.dispatch({selection:{anchor:${VIEW}.state.doc.length}})`)
const banner = () => js(`!!document.querySelector('.link-banner')`)
const bannerButton = (label) => js(`[...document.querySelectorAll('.link-banner button')].find(b=>b.textContent===${JSON.stringify(label)}).click()`)

// 1. a link to a heading: nothing is written into the target
await endOfDoc()
await insertText("see /link")
await sleep(400)
ok("typing /link raises the banner", await banner())
ok("the banner says what to do", (await js(`document.querySelector('.link-banner').textContent`)).includes("Select section to point to"))
await openNote("Second")
ok("the banner stays up across notes", await banner())
await js(`${VIEW}.dispatch({selection:{anchor:4}})`)   // in the heading
await bannerButton("Link Here")
await sleep(1200)
ok("the banner goes", !(await banner()))
ok("the source note is open again", (await doc()).includes("Intro line"), JSON.stringify(await doc()))
ok("it holds the link, where /link was", (await doc()).includes("see [Second](Second.md#second)"), JSON.stringify(await doc()))
ok("and it is on disk", (await readNoteFile("Cells.md")).includes("[Second](Second.md#second)"))
ok("the heading target needed no edit", (await readNoteFile("Second.md")) === "# Second\n\nsecond body text\n")
ok("/link itself is gone", !(await doc()).includes("/link"))

// 2. a link to a highlighted run: the run is marked in the target
await endOfDoc()
await insertText("\nand /link")
await sleep(300)
await openNote("Second")
const at = (await doc()).indexOf("body")
await js(`${VIEW}.dispatch({selection:{anchor:${at},head:${at + 4}}})`)
await bannerButton("Link Here")
await sleep(1200)
const second = await readNoteFile("Second.md")
const mark = /<mark id="(wm-[0-9a-f]{8})">body<\/mark>/.exec(second)
ok("the highlighted run is marked in the target", !!mark, JSON.stringify(second))
ok("the link carries that id", !!mark && (await doc()).includes(`[body](Second.md#${mark[1]})`), JSON.stringify(await doc()))

// 3. a block with no heading gets an anchor in front of it
await endOfDoc()
await insertText("\nlast /link")
await sleep(300)
await openNote("Second")
const where = (await doc()).indexOf("second ")
await js(`${VIEW}.dispatch({selection:{anchor:${where}}})`)
await bannerButton("Link Here")
await sleep(1200)
ok("a plain block gets an <a id> in front", /<a id="wm-[0-9a-f]{8}"><\/a>/.test(await readNoteFile("Second.md")))

// 4. cancel leaves everything alone
await endOfDoc()
await insertText("\ncancel /link")
await sleep(300)
await bannerButton("Cancel")
await sleep(300)
ok("Cancel takes the banner away", !(await banner()))
ok("and leaves the text", (await doc()).includes("cancel /link"))
await insertText(" docs/link")
await sleep(300)
ok("a path such as docs/link is not a trigger", !(await banner()))

// 5. following a link: Alt-click on the markdown, a plain click on the rendered page
await openNote("Second")
await openNote("Cells")
const rect = async (text) => JSON.parse(await js(`(()=>{const e=[...document.querySelectorAll('.wm-link, .wm-pv-link')].find(x=>x.textContent===${JSON.stringify(text)});
  if(!e) return 'null'; const r=e.getBoundingClientRect(); return JSON.stringify({x:r.x+r.width/2,y:r.y+r.height/2})})()`))
const bodyLink = await rect("body")
ok("a link is drawn as a link", bodyLink !== null)
await click(bodyLink.x, bodyLink.y); await sleep(400)
ok("a plain click on the markdown only puts the caret there", (await doc()).includes("Intro line"), JSON.stringify((await doc()).slice(0, 40)))
await click(bodyLink.x, bodyLink.y, { modifiers: ALT }); await sleep(900)
ok("Alt-click opens the note it points to", (await doc()).includes("# Second"), JSON.stringify((await doc()).slice(0, 40)))
const markAt = (await doc()).indexOf("<mark")
const head = await js(`${VIEW}.state.selection.main.head`)
ok("and lands on the part it points at", head === markAt, `${head} vs ${markAt}`)
await openNote("Cells")
// a cell with the caret in it shows its source, so the caret goes into a cell of its own below the links
await endOfDoc()
await insertText("\n\nbelow")
await sleep(300)
await setRendered(true)
const secondLink = await rect("Second")
await click(secondLink.x, secondLink.y); await sleep(900)
ok("on the rendered page a plain click follows the link", (await doc()).includes("# Second"), JSON.stringify((await doc()).slice(0, 40)))
await setRendered(false)
finish()
